### ISSUE TITLE
在本地退款回调通知正常解析，但部署到服务器上后解析出错

### ISSUE THREAD

**Issue by Stark-868** [binarywang/WxJava#998]
![image](https://user-images.githubusercontent.com/33395907/55888227-98c00100-5be1-11e9-8f6d-d31106177aaf.png)
这是出错的详细信息，麻烦您有空看一下~

**Comment by binarywang** [comment]
本地正常，服务器有问题，看起来是环境问题，建议仔细检查下

**Comment by Stark-868** [comment]
请问可以具体说下是什么环境问题吗？我在本地打包后再上传部署也不行

**Comment by binarywang** [comment]
有可能是你打包过程中导致证书出现问题，证书单独拿出来存放其他地方，通过绝对路径访问再试试看

**Comment by Stark-868** [comment]
您好，我按照您说的把证书拿出来，再打包，但解密还是出错

> ERROR (BaseWxPayServiceImpl.java:199)- 解密退款通知加密信息时出错
com.github.binarywang.wxpay.exception.WxPayException: 解密退款通知加密信息时出错
	at com.github.binarywang.wxpay.bean.notify.WxPayRefundNotifyResult.fromXML(WxPayRefundNotifyResult.java:63)
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseRefundNotifyResult(BaseWxPayServiceImpl.java:195)
	at com.cloud.printer.controller.pay.WxPayController.parseRefundNotifyResult(WxPayController.java:86)

**Comment by binarywang** [comment]
我只是提供了一个思路，具体你的环境出了什么问题，还是需要你自己去分析，看看本地环境和服务器到底有什么区别

**Comment by binarywang** [comment]
楼主有进展吗？暂时关闭，有结果麻烦直接回复即可

**Comment by Stark-868** [comment]
还是没进展，现在是通过手动查询去获取结果。

**Comment by Stark-868** [comment]
去详细看了报错的堆栈信息后，发现是以下异常导致的：
java.security.InvalidKeyException: Illegal key size or default parameters
因为美国的出口限制，Sun通过权限文件（local_policy.jar、US_export_policy.jar）做了相应限制。
所以需要把jre里的jar包替换掉，问题解决~

**Comment by binarywang** [comment]
所以还是要看根源，这个错误在wiki有提到过，是个很常见的问题

**Comment by Stark-868** [comment]
get √

**Comment by chenxianshengtwelve** [comment]
证书放在resource目录下 如果以jar方式启动 classpath：  是读取不到文件的

**Comment by binarywang** [comment]
> 证书放在resource目录下 如果以jar方式启动 classpath： 是读取不到文件的

最新版本已经解决了此问题

**Comment by anhuiwj** [comment]
> 书放在resource目录下

最新版本，请问是3.9.0吗?

**Comment by binarywang** [comment]
这个问题早解决了，你看日期选择一个比较新的版本就行了，看版本日志也可以

**Comment by anhuiwj** [comment]
好的，谢谢。自己处理好了发自我的iPhone------------------ 原始邮件 ------------------发件人: Binary Wang  <notifications@github.com>发送时间: 2020年9月19日 18:56收件人: Wechat-Group/WxJava <WxJava@noreply.github.com>抄送: anhuiwj <15555403657@163.com>, Comment <comment@noreply.github.com>主题: 回复：[Wechat-Group/WxJava] 在本地退款回调通知正常解析，但部署到服务器上后解析出错 (#998)
这个问题早解决了，你看日期选择一个比较新的版本就行了，看版本日志也可以

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Wechat-Group/WxJava/issues/998#issuecomment-695198804",
"url": "https://github.com/Wechat-Group/WxJava/issues/998#issuecomment-695198804",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xgj1988** [comment]
这个问题，我这里也出现了。。怎么搞。要  local_policy.jar 和 US_export_policy.jar这个吗？
